deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  github-token:
    secure: Me94vjRJwMdh9RIneTZxyVwwtbqHbkETqDwRWbrhPEtTNppT3WWxs2+WdS6Wo4AGygAA0amNWl5FpoL4WL+LeBJoyJIK4eGhUtaNOtgHFX744NoJow1uyNVfAC8en3T8G5J+YUdo33tWzKLtTpe0zVFy/0GPLT82p06eSkIjoyPES+rY3oA7oIXKdqwCoN7Gy0TM178L3T5SWZD9qxQCXPCZDdfqfKKUzbODzV9DN9eeR1pvHcDYo9jgCAeP3AKy8IFDTCOvfIbGhty/uBMJ5H4ukY2k5wKj0b7zsQyoEKT6eStNZt2YoChIY7Q4/6sMdvlw8We9milzlp8k1N/GLcrLoSPglBfGogEaPlxim/MQM+6mO5MP59ZkQHUbndRhLXAJzfUJAIskaqXkA6u9rsMID8SfHBNuSDbvNnh27aqmcfcHbG05Iya80omcvDhaDRYRXS1nL6qArX21uBpS/TyoQZNLAbzPXpMW6ACII48D1XzyrJRtrc/xiENcntGPAZwiFZtpF4dbwMXIBTYk8G1r6Om04X3svkGv/lakricZsb4WbCsmmtD9VeWdkgaYd2pngTJ8wii0dgy5MfoOenST105cxjtcvrEQtFOBulQ1pYsHgadFh5ko5H80HeEoHzfe9nYWesBGPji+yqd7buRtBpVcc2QZ3fJwLXRZziE=
